package com.vs.schoolmessenger.Repository

object APIMethods {

    // AUTH
    const val isCountryList = "app/api/setup/countries"
    const val isVersionCheck = "app/api/setup/version-check"
    const val isValidateUser = "app/api/auth/validate-user"
    const val isValidateOtp = "app/api/auth/validate-otp"
    const val isPasswordChange = "app/api/cred/change-password"
    const val isForgetPassword = "app/api/cred/forgot-password"
    const val isResetPassword = "app/api/cred/reset-password"
    const val isCreateNewPassword = "app/api/cred/create-new-password"
    const val isDeviceToken = "app/api/auth/device-token"
    const val isGlobalVariables = "app/api/global/global-variables"
    const val isGetDashBoard = "dashboard/api/dashboard/get-dashboard-details"
    const val isGetAds = "dashboard/api/dashboard/get-ads"
    const val getStaffList = "comm/api/recipient/get-staff-list"
    const val getSubjectList = "comm/api/recipient/get-subject-list"
    const val getStandard = "comm/api/recipient/get-standards"
    const val getStudentList = "comm/api/recipient/get-student-list"
    const val isGroupList = "comm/api/recipient/get-group-list"
    const val isGetCommmunicationlist = "comm/api/communication/list-archive"
    const val isUpdateStatusCommunication = "comm/api/communication/read-status-update"
    const val isGetCommmunicationlistload = "comm/api/communication/list"
    const val isGetVoiceHistory = "comm/api/voice/get-voice-history"
    const val isGetTextHistory = "comm/api/text-message/get-text-history"
    const val isGetHomeWorkReport = "comm/api/homework/report"
    const val isGetDailyCollectionReport = "fee/api/fee-report/daily-collection"
    const val isGetSchoolStrengthReport = "admin/api/get-school-strength"
    const val isDetailedPendingReport = "fee/api/fee-report/detailed-pending-report"
    const val isDetailedWisePendingReport = "fee/api/fee-report/detailed-class-wise-pending-report"
    const val isNoticeBoardReport = "admin/api/notice-board/get-notice"
    const val isSendText = "comm/api/text-message/send-text"
    const val isSendHomeWork = "comm/api/homework/send-homework"
    const val isSendVoice = "comm/api/voice/send-voice"
    const val isUpdateStatusArchive = "comm/api/communication/read-status-update-archive"
    const val isGetAcademicYear = "comm/api/recipient/get-academic-year-list"
    const val isHomeWorkDetails="comm/api/homework/list"

    const val send_homework = "comm/api/homework/send-homework"
    const val homework_reports = "comm/api/homework/get-homework-report"
    const val homework_list = "comm/api/homework/get-homework-list"
    const val homework_list_archive = "comm/api/homework/list-archive"
    const val send_attachments = "comm/api/attachment/send-attachment"
    const val attachments_list = "comm/api/communication/attachment-list"
    const val attachments_list_archive = "comm/api/communication/attachment-list-archive"


    const val punch_giometric_attendance =  "staff-attd/api/geometric/entry-using-app"
    const val add_giometric_location =  "staff-attd/api/geometric/set-geometric-location"
    const val giometric_location_history =  "staff-attd/api/geometric/get-geometric-location-history"
    const val staff_locations =  "staff-attd/api/geometric/get-staff-geometric-location"
    const val remove_location =  "staff-attd/api/geometric/remove-geometric-location"
    const val update_location =  "staff-attd/api/geometric/update-geometric-location"
    const val giometric_staff_attendance_report =  "staff-attd/api/geometric/geometric-staff-attendance-report"
    const val giometric_principal_attendance_report =  "staff-attd/api/geometric/geometric-principal-attendance-report"
    const val punch_history =  "staff-attd/api/geometric/geometric-punch-history"
    const val student_report= "admin/api/get-student-report"
    const val IsGetEventReport = "admin/api/school-event/get-event"
    const val send_absentee_sms = "stud-attd/api/attendance/send-absentees-sms-with-session-type"
    const val get_student_attendance_report_for_scchool = "stud-attd/api/attendance/student-attendance-report"
    const val get_child_attendance_report = "stud-attd/api/attendance/get-absent-dates-for-child"
    const val IsGetHolidayReport = "admin/api/school-event/view-holidays"
    const val getabsenteescountbydate = "stud-attd/api/attendance/get-absentees-count-by-date"

    const val getabsenteesstudentbydate = "stud-attd/api/attendance/get-absentees-students-by-date"

    const val sendnotice = "admin/api/notice-board/send-notice"
    const val sendevent = "admin/api/school-event/send-event"
    const val sendAttachment = "comm/api/attachment/send-attachment"
    const val attachmentList = "comm/api/attachment/list"
    const val attachmentListArchive = "comm/api/attachment/list-archive"
    const val leave_request_apply = "comm/api/leave-req/apply"
    const val getleaverequest = "comm/api/leave-req/list"
    const val isleaverequestapprove = "comm/api/leave-req/update-status"
    const val getlpStaffReport = "lms/api/lesson-plan/staff-report"
    const val getlpViewReport = "lms/api/lesson-plan/view"
    const val getlpeditReport = "lms/api/lesson-plan/get-data-for-edit"
    const val isupdatelessonplan = "lms/api/lesson-plan/update"
}




