package com.vs.schoolmessenger.Repository

object APIMethods {

    // AUTH
    const val isCountryList = "app/api/setup/countries"
    const val isVersionCheck = "app/api/setup/version-check"
    const val isValidateUser = "app/api/auth/validate-user"
    const val isValidateOtp = "app/api/auth/validate-otp"
    const val isPasswordChange = "app/api/cred/change-password"
    const val isForgetPassword = "app/api/cred/forgot-password"
    const val isResetPassword = "app/api/cred/reset-password"
    const val isCreateNewPassword = "app/api/cred/create-new-password"
    const val isDeviceToken = "app/api/auth/device-token"
    const val isGlobalVariables = "app/api/global/global-variables"

    //    const val isGetDashBoard = "dashboard/api/dashboard/get-dashboard-details"
    const val isGetDashBoard = "dashboard/api/dashboard/menus"
    const val isGetDashBoardCount = "dashboard/api/dashboard/menu-counts"
    const val isGetAds = "dashboard/api/dashboard/get-ads"
    const val isNotifications = "dashboard/api/dashboard/notifications"
    const val getStaffList = "comm/api/recipient/get-staff-list"
    const val getSubjectList = "comm/api/recipient/get-subject-list"
    const val getStandard = "comm/api/recipient/get-standards"
    const val getStudentList = "comm/api/recipient/get-student-list"
    const val isGroupList = "comm/api/recipient/get-group-list"
    const val isGetCommmunicationlist = "comm/api/communication/list-archive"
    const val isUpdateStatusCommunication = "comm/api/communication/read-status-update"
    const val isGetCommmunicationlistload = "comm/api/communication/list"
    const val isGetVoiceHistory = "comm/api/voice/get-voice-history"
    const val isGetTextHistory = "comm/api/text-message/get-text-history"
    const val isGetHomeWorkReport = "comm/api/homework/report"
    const val isHomeWorkUpdate = "comm/api/homework/update"
    const val isEventUpdate = "admin/api/school-event/update"
    const val isAttachmentUpdate = "comm/api/attachment/update"
    const val isHomeWorkDelete = "comm/api/homework/delete"
    const val isAttachmentDelete = "comm/api/attachment/delete"
    const val isGetAssignmentReport = "comm/api/assignment/report"
    const val isAssignmentSubmittedList = "comm/api/assignment/submissions-list"
    const val isAssignmentDelete = "comm/api/assignment/delete"
    const val isGetDailyCollectionReport = "fee/api/fee-report/daily-collection"
    const val isGetSchoolStrengthReport = "admin/api/get-school-strength"
    const val isDetailedPendingReport = "fee/api/fee-report/detailed-pending-report"
    const val isDetailedWisePendingReport = "fee/api/fee-report/detailed-class-wise-pending-report"
    const val isNoticeBoardReport = "admin/api/notice-board/get-notice"
    const val isNoticeBoardUpdate = "admin/api/notice-board/update"
    const val isNoticeBoardStaffReport = "admin/api/notice-board/report"
    const val isSendText = "comm/api/text-message/send-text"
    const val isSendHomeWork = "comm/api/homework/send-homework"
    const val isAssignmentSend = "comm/api/assignment/send-assignment"
    const val isAssignmentUpdate = "comm/api/assignment/update"
    const val isSendVoice = "comm/api/voice/send-voice"
    const val isUpdateStatusArchive = "comm/api/communication/read-status-update-archive"
    const val isGetAcademicYear = "comm/api/recipient/get-academic-year-list"
    const val isHomeWorkDetails = "comm/api/homework/list"
    const val isHomeWorkComplete = "comm/api/homework/mark-complete"

    const val send_homework = "comm/api/homework/send-homework"
    const val homework_reports = "comm/api/homework/get-homework-report"
    const val homework_list = "comm/api/homework/get-homework-list"
    const val homework_list_archive = "comm/api/homework/list-archive"
    const val send_attachments = "comm/api/attachment/send-attachment"
    const val attachments_list = "comm/api/communication/attachment-list"
    const val attachments_list_archive = "comm/api/communication/attachment-list-archive"
    const val punch_giometric_attendance = "staff-attd/api/geometric/entry-using-app"
    const val add_giometric_location = "staff-attd/api/geometric/set-geometric-location"
    const val giometric_location_history = "staff-attd/api/geometric/get-geometric-location-history"
    const val staff_locations = "staff-attd/api/geometric/get-staff-geometric-location"
    const val remove_location = "staff-attd/api/geometric/remove-geometric-location"
    const val update_location = "staff-attd/api/geometric/update-geometric-location"
    const val giometric_staff_attendance_report =
        "staff-attd/api/geometric/geometric-staff-attendance-report"
    const val giometric_principal_attendance_report =
        "staff-attd/api/geometric/geometric-principal-attendance-report"
    const val punch_history = "staff-attd/api/geometric/geometric-punch-history"
    const val student_report = "admin/api/get-student-report"
    const val IsGetEventReport = "admin/api/school-event/get-event"
    const val IsGetEventSchoolReport = "admin/api/school-event/report"
    const val send_absentee_sms = "stud-attd/api/attendance/send-absentees-sms-with-session-type"
    const val get_student_attendance_report_for_scchool =
        "stud-attd/api/attendance/student-attendance-report"
    const val get_child_attendance_report = "stud-attd/api/attendance/get-absent-dates-for-child"
    const val get_certificate_types = "comm/api/certificate/types"
    const val send_certificate_request = "comm/api/certificate/send-request"
    const val get_certificates_list = "comm/api/certificate/request-list"
    const val get_time_table = "lms/api/time-table/get-schedule"
    const val IsGetHolidayReport = "admin/api/school-event/view-holidays"
    const val getabsenteescountbydate = "stud-attd/api/attendance/get-absentees-count-by-date"
    const val getabsenteesstudentbydate = "stud-attd/api/attendance/get-absentees-students-by-date"
    const val sendnotice = "admin/api/notice-board/send-notice"
    const val sendevent = "admin/api/school-event/send-event"
    const val sendAttachment = "comm/api/attachment/send-attachment"
    const val attachmentList = "comm/api/attachment/list"
    const val attachmentReportList = "comm/api/attachment/report"
    const val get_category_list = "get_category_list"
    const val attachmentListArchive = "comm/api/attachment/list-archive"
    const val leave_request_apply = "comm/api/leave-req/apply"
    const val getleaverequest = "comm/api/leave-req/list"
    const val isleaverequestapprove = "comm/api/leave-req/update-status"
    const val getlpStaffReport = "lms/api/lesson-plan/staff-report"
    const val getlpViewReport = "lms/api/lesson-plan/view"
    const val getlpeditReport = "lms/api/lesson-plan/get-data-for-edit"
    const val getlpcreateReport = "lms/api/lesson-plan/get-data-for-add"
    const val isupdatelessonplan = "lms/api/lesson-plan/update"
    const val iscreatelessonplan = "lms/api/lesson-plan/add"
    const val islessonplandelete = "lms/api/lesson-plan/delete"
    const val get_campaigns = "get_campaigns"
    const val my_coupons = "my_coupons"
    const val get_campaign_details = "get_campaign_details"
    const val activate_coupon = "activate_coupon"
    const val staff_details_for_chat = "/comm/api/interaction/staff-details-for-chat"
    const val student_details_for_chat = "/comm/api/interaction/classes-for-chat"

    const val get_staff_answers = "/comm/api/interaction/get-staff-answers"
    const val staff_get_questions = "/comm/api/interaction/staff-get-questions"
    const val student_ask_question = "/comm/api/interaction/student-ask-question"
    const val staff_ans_question = "/comm/api/interaction/staff-ans-question"
    const val get_exams = "/exam/api/exam/get-exams"
    const val exam_list = "/exam/api/exam/list"
    const val view_marks = "/exam/api/exam/view-marks"
    const val progress_card = "/exam/api/exam/get-progress-card"
    const val isleaverequestupdate = "comm/api/leave-req/update"
    const val isleaverequestdelete = "comm/api/leave-req/delete"
    const val isEventDelete = "admin/api/school-event/delete"
    const val isnoticeboarddelete = "admin/api/notice-board/delete"
    const val isEventCategories = "admin/api/school-event/categories"
    const val isleavecategories = "comm/api/leave-req/leave-categories"
    const val isAssignmentlist = "comm/api/assignment/list"
    const val isSubmitAssignment = "comm/api/assignment/submit-assignment"
    const val isstudentstats = "stud-attd/api/attendance/student-stats"
    const val isAssignmentMySubmission = "comm/api/assignment/my-submissions"
    const val islsrwskillsreport = "lms/api/lsrw/skills-report"
    const val islsrwStudentlist = "lms/api/lsrw/submission-list"
    const val islsrwSkillCreate = "lms/api/lsrw/create-skill"
    const val islsrwSkillSubmit = "lms/api/lsrw/submit-skill"
    const val islsrwSkilllist = "lms/api/lsrw/skill-list"
    const val islsrwstats = "lms/api/lsrw/stats"
    const val islsrwremarkupdate = "lms/api/lsrw/remark"


    // PTM API CALLS

    const val isCreateSlots = "ptm/api/ptm-schedule/create-slots"
    const val isSlotDetailsForStaff = "ptm/api/ptm-schedule/slot-details-for-staff"
    const val isSlotCancelAndReOpen = "ptm/api/ptm-schedule/cancel-and-reopen-slot"
    const val isSlotCancelAndClose = "ptm/api/ptm-schedule/cancel-and-close-slot"
    const val isDatewiseBookedSlots = "ptm/api/ptm-schedule/datewise-booked-slots"
    const val isBookingForStudent = "ptm/api/ptm-schedule/book-slots-for-student"
    const val isSlotsAvailabilityForStudent =
        "ptm/api/ptm-schedule/teacherwise-slots-availability-for-student"
    const val isAvailableSlotsCountForStudent =
        "ptm/api/ptm-schedule/available-slots-count-for-student"
    const val isCancelByStudent = "ptm/api/ptm-schedule/cancel-slot-by-student"
    const val isValidateForStaffToSlot = "ptm/api/ptm-schedule/validate-slots-for-staff"
    const val isSlotHistoryForStudent = "ptm/api/ptm-schedule/slot-history-for-student"
    const val isSubjectListClassTeacher = "ptm/api/ptm-schedule/subject-list-with-class-teacher"


    const val isGetQuizExamList = "lms/api/quiz/quiz-exam-list"
    const val isGetQuestion = "lms/api/quiz/get-questions"
    const val isSubmitQuiz = "lms/api/quiz/submit"
    const val isGetMySubmission = "lms/api/quiz/my-submissions"

    const val isCreateQuiz = "lms/api/quiz/create-quiz"
    const val isGetExamQuizReport = "lms/api/quiz/report"
    const val isGetCheckLevel = "lms/api/quiz/check-level"
    const val isGetQuizQuestionReport = "lms/api/quiz/questions-report"
    const val isGetQuizSubmissionList = "lms/api/quiz/submission-list"
    const val isGetPickFromQBank = "lms/api/quiz/pick-from-qbank"
    const val isAddQuestion = "lms/api/quiz/add-question"


    const val isGetMessageFromStaff = "comm/api/msg-from-management/get-messages-staff"
    const val isGetMessageFromStaffArchive = "comm/api/msg-from-management/get-messages-staff-archive"
    const val isGetPauketPoints = "dashboard/api/pauket/get-points"
    const val isSpentPoints = "dashboard/api/pauket/spent-points"
    const val isAddRewardPoints = "dashboard/api/pauket/add-points"
    const val isParentprofilelist = "admin/api/student-profile/list"
    const val isSchoolprofilelist = "admin/api/staff-profile/list"
    const val islsrwmysubmission = "lms/api/lsrw/my-submissions"
    const val ispresubmission = "admin/api/student-profile/pre-submission"
    const val fee_student_invoice = "fee/api/fee-details/student-invoice"
    const val fee_student_invoice_details = "fee/api/fee-details-invoice-details"
    const val childhomework_standard = "admin/api/school-event/target-details"
    const val assignment_childhomework = "admin/api/school-event/target-details"
    const val attachment_childhomework = "admin/api/attachment/target-details"

    const val getmysubmissionedit = "comm/api/assignment/update-submission"
    const val ismysubmissiondelete = "comm/api/assignment/delete-submission"
    const val dashboard_newupdates = "dashboard/api/dashboard/new-updates"
    const val getAttendanceStudentList = "stud-attd/api/attendance/student-list"


    const val isblockstudent = "/comm/api/interaction/block-student"
    const val isblockstudentlist = "/comm/api/interaction/blocked-students"

}




