package com.vs.schoolmessenger.School.Hostel.Model

enum class FragmentType {
   BEDOCCUPIED, TOTALSTUDENT, PENDINGISSUES, OUTPASSREQUESTS, MESSTIMETABLE,ATTENDANCEHISTORYHOSTEL,ROOMATTENDANCE,FEEMANAGEMENT
}
