## 设计器地址
serverUrl=Token

############## 以下配置一般无需修改 ##############
## 客户端调试端口
#debugClientPort=28888
## 是否打印客户端异常堆栈信息
#printStacktraceEnabled=false
## 是否打印 WebSocket 调试日志
#printWebSocketLogEnabled=false
## 是否打印 Debug 调试日志
#printDebugLogEnabled=false

